apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: capi-mgm
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'app-cilium-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/cilium/chart
        helm:
          releaseName: cilium
          values: []
#          values: ../overlays/{{cluster}}/values.yaml
      destination:
        server: '{{url}}'
        namespace: kube-system