apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-cni
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'app-cilium-cni-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/cilium-cni/chart
        helm:
          releaseName: cilium
          valueFiles:
          - overlays/{{name}}/values.yaml
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: false
          selfHeal: false