apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: capi-mgm
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'app-kyverno-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/kyverno/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: false