apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ccm-hcloud
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: 'app-ccm-hcloud-{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/ccm-hcloud/overlays/{{name}}
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: false