apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ccm-hcloud
spec:
  generators:
  - list:
      elements:
      - cluster: capi-mgm
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-ccm-hcloud'
    spec:
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/ccm-hcloud/overlays/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd