apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ccm-hcloud
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: capi-mgm
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'app-ccm-hcloud-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/m-over/capi-argocd-bootstrap.git"
        targetRevision: HEAD
        path: apps/ccm-hcloud/overlays/{{cluster}}/values.yaml
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: false